### ISSUE TITLE
Assign mutations and actions on modules

### ISSUE THREAD

**Issue by 0xmaayan** [leonardovilarinho/vue-offline-worker#1]
Hey, Thanks for the package, it looks like what I need but I am having a hard time to config it.

How can I implement this ->

`
actions: Object.assign(actions, offline.actions),
mutations: Object.assign(mutations, offline.mutations)
`

When my store structure is like this ->

`export default new Vuex.Store({
  modules: {
    moduleA,
    moduleB,
    moduleC
  }
})
`

Every module has actions and mutations.

thanks,

**Comment by leonardovilarinho** [comment]
Hello @msbir , sorry for the delay.

Use something like this:

```
export default new Vuex.Store({
  modules: {
    moduleA: {
      ...moduleA,
      mutations: Object.assing(moduleA.mutations, offline.mutations),
      actions: Object.assing(moduleA.actions, offline.actions)
   },
   ...
  }
})
```
